# Default planner to use if not specified
default_planner: "MCGS"

experiment:
  render_mode: "ansi"
  save_replay: true
  computational_budget_max: 50
  time_budget_max: 20.0
  sleep_time: 0.1
  max_steps: 40
  num_episodes: 10

environment:
  name: "NavigationEnvSingleIntegratorUnicycle-v0"
  # Environment parameters
  dt: 1.0
  atol: 0.3
  rtol: 0.0
  multi_step_count: 5
  obstacle_mode: "circles"
  render_sleep: 0.0
  plan_in_space_time: true
  default_step_divisor: 1
  sparse_reward: true

planners:
  MCGS:
    config:
      expand_n_times: 1
      expand_n_times_min: 1
      expand_n_times_max: 1
      sample_best_X_actions: 10
      kappa: 0.3
      alpha: 0.8
      k: 30
      radius_threshold: 1.5
      progressive_widening_method: "default"
      epsilon: 0.1
      abstraction_refinement_exponent: -0.5
      c_uct: 0.5
      plan_in_space_time: true
      use_controller: true
      tracking_tolerance: 0.2
      yield_mode: 'Q'
      random_rollout_n_times: 1
      random_rollout_length: 4
      force_exact_update: true
  CMCGS:
    config:
      min_graph_length: 2
      rollout_length: 3
      clustering_alg: "agglomerative"
      elite_ratio: 0.06497869807787184
      optimal_prob: 0.0653597982920884
      optimal_n_top: 15
      optimal_range: 0.9971984073593032
      max_n_clusters: 2147483646  # np.iinfo(np.int32).max - 1
      min_update_divisor: 1.4312025565499444
      alpha: 5
      beta: 10

