name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    container: rust:1.87
    defaults:
      run:
        working-directory: ./firmware
    strategy:
      matrix:
        feature: ["", "zumo", "three-pi"]   # "" = (v0)
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: 'recursive'

      - name: Install toolchain
        run: |
          rustup target add thumbv6m-none-eabi
          cargo install flip-link

      - name: Build library
        run: |
          if [ -z "${{ matrix.feature }}" ]; then
            cargo build --release --target thumbv6m-none-eabi
          else
            cargo build --release --target thumbv6m-none-eabi --features ${{ matrix.feature }}
          fi

      - name: Run Linter
        run: |
          rustup component add clippy
          if [ -z "${{ matrix.feature }}" ]; then
            cargo clippy --target thumbv6m-none-eabi --bins --examples --lib
          else
            cargo clippy --target thumbv6m-none-eabi --bins --examples --lib --features ${{ matrix.feature }}
          fi
